### PR TITLE
added collapsable sections

### PR DESCRIPTION
**Pull request by storyaddict**
This PR adds collapse-able sections to the "Before You Open a Ticket" article. 

This makes a long, multi-part doc much more readable and easily navigable.

### CODE REVIEW

**Comment by jacobgkau** [comment]
Not sure if you saw the review on https://github.com/system76/docs/pull/959, but it may be good to pause opening new PRs doing this until the strategy as a whole is nailed down.

**Comment by storyaddict** [comment]
@jacobgkau just saw your other comment. Investigating.

**Comment by gangwerz** [comment]
PR #972 may change the trajectory of these changes.

**Comment by storyaddict** [comment]
Closing these collapsible section PRs for now as we may be moving to mdbook.

**Pull request closed without merging**
