### PR TITLE
Update homepage hero styles

### PR DESCRIPTION
**Pull request by btkostner**
This updates the top of the support.system76.com page to be a little more inviting and easy to read. Paging @ahoneybun, @storyaddict, and @Socialhappiness 

Todo:
- [x] Work on copy
- [x] Finalize links and actions

A preview of what it looks like **outdated**:

Screenshot from 2021-06-29 20 57 16

### CODE REVIEW

**Comment by storyaddict** [comment]
Would it be possible to have a link to the "Before You Open a Support Ticket" article on the page where customers type in their ticket information?

**Comment by btkostner** [comment]
Yep, we can do that. I'd keep in mind that the whole flow is going to change with Shopify though.

**Comment by storyaddict** [comment]
the main thing is I want people to be prompted to review that article before opening a ticket. If we have to adapt to Shopify later, that's fine.

**Comment by btkostner** [comment]
@Socialhappiness are you ok with a direct email button like what's in the photo? If yes, what email address should it be, and if not, do you have any other action you would like there, or just remove it?

**Comment by btkostner** [comment]
Alright. Emma signed off on it with the removal of the email button. I'm working on the artoo PR to mention the concern @storyaddict had.

**Review by burden — APPROVED** [review]
Looks great @btkostner! Such a huge improvement. 

Personal preference (no action needed): the cards in mobile landscape might look better expanded: 
image

**Pull request merged**
