### PR TITLE
Update printer articles

### PR DESCRIPTION
**Pull request by Ampersandstorm**
This PR updates both the Ubuntu and Pop!_OS printer articles:

- Clean up grammar 
- Update and clarify instructions to download the Brother driver tool
- Move and expand upon instructions to access CUPS and sharing a printer with CUPS
- Include additional screenshots
- Add updated style and formatting conventions

### CODE REVIEW

**Review by thomas-zimmerman — APPROVED** [review]
I like this update. Let's see if we can get it live

**Review by ahoneybun — APPROVED** [review]
LGTM

**Comment by Nikongen** [comment]
Hi there,

i found one small mistake in the printer articles.
The last two commands in [this article](https://support.system76.com/articles/add-a-printer-pop/) are missing  `install`

Commands on the website:
```
sudo apt --reinstall cups cups-client
sudo apt --reinstall system-config-printer
```

Leads to error(german, deepl english tranls.)
```
E: Befehlszeilenoption »--reinstall« kann in Kombination mit den anderen Optionen nicht interpretiert werden.
E: Command line option »--reinstall« cannot be interpreted in combination with the other options.

```

What it should be:
```
sudo apt install --reinstall cups cups-client
sudo apt install --reinstall system-config-printer
```

**Comment by ahoneybun** [comment]
@Nikongen this should be fixed in https://github.com/system76/docs/pull/1095 so thank you for that feedback!

**Pull request merged**
