### PR TITLE
Updates to the pritner page for pop.

### PR DESCRIPTION
**Pull request by thomas-zimmerman**
drop reference to cononical
add package info to run hp-setup

### CODE REVIEW

**Comment by ahoneybun** [comment]
Both articles are still very different, why is that?

**Comment by ahoneybun** [comment]
I would also change Software & Updates to the Pop Shop and Repoman.

**Comment by doomspork** [comment]
Bah! Sorry for the hassle. @thomas-zimmerman could you update your PR to point to `master` and not `gh-pages`? We should be good to re-open and merge then.

**Comment by thomas-zimmerman** [comment]
Updated changes and made new pull request vs. master

**Pull request closed without merging**
