### PR TITLE
Publishing CodeWeavers  case study with James Ramey

### PR DESCRIPTION
**Pull request by kenhara76**

### CODE REVIEW

**Comment by kenhara76** [comment]
My thought was that the arrow indicates it is going to be downloaded onto their machine (which is what happens when clicking the link), whereas the right arrow indicates it's going to change their window when they click on it. 

A few examples where this is the case elsewhere:

screenshot from 2019-02-20 10-37-20

screenshot from 2019-02-20 10-35-39

screenshot from 2019-02-20 10-36-59

That said, I can submit a separate PR changing this across all of the case studies if you prefer?

**Comment by kenhara76** [comment]
In fact, we could add an underline below the arrow to make it even more consistent with these examples?

**Comment by ahoneybun** [comment]
Fair enough.

**Comment by ahoneybun** [comment]
So it looks like the PDF for that case study is not in the folder so I get a 404 when I click on that link.

**Pull request merged**
