### PR TITLE
Update the steps to generate a log file in freezing-behavior.md

### PR DESCRIPTION
**Pull request by ws909**
The existing explanation was for a previous version of the system.

### CODE REVIEW

**Review by ahoneybun — CHANGES_REQUESTED** [review]
I think we should have both and just update the steps for the driver since it also applies to system76 systems.

**Comment by ahoneybun** [comment]
> Do you mean that the old explanation should be kept there? It's already listed on the page linked to at the end. It was moved to the Settings application a few OS versions ago now.
> 
> I have not checked if other help pages also have this outdated explanation; if changes are made, they should probably be made for every help page.

No it is in both the Settings (only on Pop!_OS) and in the System76 Driver for both Ubuntu and Pop!_OS.

**Comment by ws909** [comment]
Is it better to just remove the detailed explanation from the page, then, and rely on the link? For instance, 

>  Please attach a log file in a reply to this ticket. For a detailed list of steps to generate a log file, or if you are having any issues, you can refer to this [article](/articles/log-files).

In all fairness, I do find it a bit strange that this section exists in the first place. I haven't made any contributions here before, so my opinion certainly doesn't carry a lot of weight. I did however find the section quite out of place when I read it. I was looking through a few troubleshooting pages, and it was the first time I heard anything of support tickets. I was not aware of this option, and when looking at the site again, it did not seem to be readily available anywhere (eventually found a link buried in [here](https://support.system76.com/articles/before-you-open-a-support-ticket/)). It would be a reasonable section to include if it was sent by a support agent as a response to an already opened ticket, but it was out of place when looking at that page outside of that context. Other similar troubleshooting pages do not have this section.

**Comment by ahoneybun** [comment]
> Is it better to just remove the detailed explanation from the page, then, and rely on the link? For instance,
> 
> > Please attach a log file in a reply to this ticket. For a detailed list of steps to generate a log file, or if you are having any issues, you can refer to this [article](/articles/log-files).
> 
> In all fairness, I do find it a bit strange that this section exists in the first place. I haven't made any contributions here before, so my opinion certainly doesn't carry a lot of weight. I did however find the section quite out of place when I read it. I was looking through a few troubleshooting pages, and it was the first time[1](#user-content-fn-1-e16d9e7dfd9b32ddfd7136a699fb71fe) I heard anything of support tickets. I was not aware of this option, and when looking at the site again, it did not seem to be readily available anywhere (eventually found a link buried in [here](https://support.system76.com/articles/before-you-open-a-support-ticket/)). It would be a reasonable section to include if it was sent by a support agent as a response to an already opened ticket, but it was out of place when looking at that page outside of that context. Other [similar troubleshooting page](https://support.system76.com/articles/login-loop-pop/)s do not have this section.
> ## Footnotes
> 
>     1. Actually, I see now that the top of the page has "If you have a support ticket open"; I was still a bit confused at the at the section. I may have missed this note while looking through the page and scrolling down. [↩](#user-content-fnref-1-e16d9e7dfd9b32ddfd7136a699fb71fe)

That is for customers who have system76 hardware since they would send the logs to one of the support folks such as myself.

**Review by ahoneybun — APPROVED** [review]
I believe this should be good now.

**Review by leviport — CHANGES_REQUESTED** [review]
@ahoneybun can you fix that lint issue? Other than that, this looks good.

**Review by leviport — APPROVED** [review]
Thanks!

**Review by ahoneybun — APPROVED** [review]

**Pull request merged**
