### PR TITLE
Bottles setup guide in Pop!_OS

### PR DESCRIPTION
**Pull request by Ampersandstorm**
Created a basic guide for installing Bottles in Pop!_OS, creating a Bottle, and installing a Windows .exe. This article was created per thre quest in issue #953

### CODE REVIEW

**Comment by Ampersandstorm** [comment]
These remaining linter issues are caused by another article that is not intended to be part of this PR (pop-refresh-os.md). I don't believe I edited that article, but my apologies if I caused some issue.

**Comment by jacobgkau** [comment]
> These remaining linter issues are caused by another article that is not intended to be part of this PR (pop-refresh-os.md). I don't believe I edited that article, but my apologies if I caused some issue.

`pop-refresh-os.md` is not included in master, and that file is checked into your PR, so your PR is adding it. If you don't want it to be part of this PR, please remove it.

**Review by ahoneybun — CHANGES_REQUESTED** [review]
Is there a reason that Bottles is not using the system default theme which is Pop Dark? It looks odd since other screenshots are using the Pop theme.

**Review by ahoneybun — APPROVED** [review]

**Comment by mirkobrombin** [comment]
> Is there a reason that Bottles is not using the system default theme which is Pop Dark? It looks odd since other screenshots are using the Pop theme.

Sorry for the intrusion. It's flatpak's fault, installing the Pop theme package from flathub fix it. I don't know why this happens, I haven't put any blocks in Bottles that prevent the use of themes.
image

**Review by storyaddict — APPROVED** [review]
Nice addition!

**Comment by storyaddict** [comment]
@system76/quality-assurance any objection to me merging this?

**Review by jacobgkau — APPROVED** [review]
Instructions are working.

QA review passed: [docs-pr985.md](https://github.com/system76/docs/files/8854845/docs-pr985.md)

**Pull request merged**
