### PR TITLE
route typo fix

### PR DESCRIPTION
**Pull request by LobbyLobster**
My system broke after latest Nvidia driver updates and while trying to fix the problem realized package manager repair commands link was forwarding to the wrong route.

### CODE REVIEW

**Comment by LobbyLobster** [comment]
Apparently I also had to add .md extension and this is not the only wrong route all links forwarding to /article/ are broken since it doesn't exists.

**Comment by ahoneybun** [comment]
The missing / was the correct fix as you can see the other links work with it. Thank you for this PR and letting us know about the issue!

**Comment by ddotthomas** [comment]
I just closed a pull request I made as I hadn't checked for this one. I think changing article/package-manager-pop to /articles/package-manager-pop will be the easiest fix.

**Comment by ahoneybun** [comment]
@LobbyLobster we'll want to keep this open as we can use it to fix this issue.

**Review by ahoneybun — APPROVED** [review]
LGTM :tada:

**Comment by LobbyLobster** [comment]
Sorry I'm not accustomed to contributing. Thought it's already done and I had to close it. Thanks for letting me know!

**Pull request merged**
