### PR TITLE
Update cuda.md, replace cuda 12.2 by 12.5

### PR DESCRIPTION
**Pull request by UrielCh**
Cuda 12.2 is deprecated, and display nasty warning.

the driver version 555 is currently 6 day old.

the driver version 550 was built on top of cuda 12.4.

### CODE REVIEW

**Comment by ahoneybun** [comment]
Since 555 is not stable yet I believe we would just swap 12.2 with 12.4, is that not correct?

**Comment by UrielCh** [comment]
550 is installed by default out of the box and works with cuda 12.4.

the current PR will be ... fully valid in a few days or week, let me switch to 12.4

**Comment by UrielCh** [comment]
I had replace nvidia-driver-555 by nvidia-driver-550
and cuda 12.5 by 12.4.

that should be a stable version.

**Review by thomas-zimmerman — APPROVED** [review]
Thank you for the PR @UrielCh 

Changes look correct for the update to 12.5

**Review by jacobgkau — APPROVED** [review]
Tested this on an NVIDIA system & the updated steps work fine. The deprecation notice no longer appears with the new container image.

**Pull request merged**
