### PR TITLE
Tensorman

### PR DESCRIPTION
**Pull request by ahoneybun**
Don't merge until Pop 19.10 is released.

### CODE REVIEW

**Comment by jackpot51** [comment]
Is this obsoleted by https://github.com/system76/docs/pull/211?

**Comment by ahoneybun** [comment]
I believe we would merge this first and then #211 .

**Comment by jackpot51** [comment]
#211 contains the same changes as this, so why would we need to merge this?

**Comment by ahoneybun** [comment]
@jackpot51 I *believed* it was. If this is not the case then we can just merge the other one.

**Comment by jackpot51** [comment]
Let's see what happens when #211 is merged. If anything appears missing we can revisit this one

**Pull request closed without merging**
