### PR TITLE
Adds section and link to download the OS image

### PR DESCRIPTION
**Pull request by CrustyBarnacle**
Adds section and link to download the OS image, as is expected bases on the opening paragraph "
The following guide describes how to download the Pop!\_OS.iso image, write it to a flash drive, and install it on the hardware of your choice."

### CODE REVIEW

**Comment by ahoneybun** [comment]
Thank you for your PR! We do have a link to the live disk article which goes over downloading the OS image already.

http://support.system76.com/articles/live-disk/

**Comment by CrustyBarnacle** [comment]
OK, that was not clear, but I do see the link in the linked-to article. Still think the section/article title could be improved to _Download Image and Make Bootable Drive_, or such.

**Comment by ahoneybun** [comment]
@storyaddict what are your thoughts on this?

**Review by storyaddict — APPROVED** [review]
Good quality of life addition. Thanks @CrustyBarnacle

**Pull request merged**
