### PR TITLE
Correct typo in roadmap

### PR DESCRIPTION
**Pull request by strangebreww**
Looks like a typo to me.

### CODE REVIEW

**Comment by ahoneybun** [comment]
@strangebreww it looks like we need to update the branch that this is based on though I don't see an option for that so you may need to rebase.

**Comment by strangebreww** [comment]
@ahoneybun rebased. Thanks for the heads-up.

**Review by storyaddict — APPROVED** [review]
Trying to submit my review again to see if this can refresh things and allow the PR to be merged.

**Comment by storyaddict** [comment]
Replacing this PR (including it's fix) with this PR https://github.com/system76/docs/pull/814 which includes additional improvements. 

Unable to update/merge this PR so closing it. Thanks again @strangebreww

**Pull request closed without merging**
