### PR TITLE
Update package manager

### PR DESCRIPTION
**Pull request by ahoneybun**
Address issue: https://github.com/system76/docs/issues/939

### CODE REVIEW

**Review by thomas-zimmerman — COMMENTED** [review]
Updating to be explicit on what files are helpful

**Review by thomas-zimmerman — CHANGES_REQUESTED** [review]
@ahoneybun Thoughts on the updated wording?

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
The commands work as expected, but I'm not sure about the capitalization of `Apt/Dpkg`. I would recommend it be swapped with `APT/dpkg` based on the Wikipedia pages.

**Comment by jacobgkau** [comment]
For what it's worth, we used `Apt` at the beginning of sentences or titles a couple of times in the unfinished Pop!_Docs: https://github.com/pop-os/docs/blob/main/src/manage-apps/fix-packages.md, https://github.com/pop-os/docs/blob/main/src/manage-apps/using-terminal.md 

Although it is technically `APT` according to upstream (or `apt` when referring to the command): https://salsa.debian.org/apt-team/apt 

Debian does refer to `Dpkg` with that capitalization e.g. in the names of its development teams (as well as config flags): https://wiki.debian.org/Teams/Dpkg, https://salsa.debian.org/dpkg-team

**Comment by thomas-zimmerman** [comment]
Updated article to address APT discussion. Please squish changes if merging.

**Comment by jacobgkau** [comment]
Why'd you change `Pop!_Shop` to `Pop Shop` in the Pop article?

**Comment by ahoneybun** [comment]
> Why'd you change `Pop!_Shop` to `Pop Shop` in the Pop article?

Should be fixed now.

**Review by n3m0-22 — APPROVED** [review]
Looks good.

**Review by jacobgkau — APPROVED** [review]

**Review by thomas-zimmerman — APPROVED** [review]
I would like to get these pending changes out. It looks like the APT/Dpkg concernss are addressed

**Pull request merged**
