### PR TITLE
Setting up Protonmail with Geary

### PR DESCRIPTION
**Pull request by ahoneybun**
This PR adds an article to setup ProtonMail using their Bridge in Geary.

### CODE REVIEW

**Review by storyaddict — CHANGES_REQUESTED** [review]
Add instructions for Fastmail, Gmail and iCloud Mail.

**Comment by ahoneybun** [comment]
@storyaddict I've added Gmail and will work on Fastmail unless you want to.

**Comment by ahoneybun** [comment]
Added the Fastmail section.

**Review by storyaddict — APPROVED** [review]
reviewed changes and added the iCloud section.

**Pull request merged**
