### PR TITLE
cudnn-10.1 is not availible

### PR DESCRIPTION
**Pull request by TashaSkyUp**
sudo apt install system76-cudnn-10.1 fails so suggest using 10.0

### CODE REVIEW

**Comment by brs17** [comment]
Currently 10.1 does not work in 19.10 but does work in 18.04 so this distinction should be mentioned.

**Comment by mmstick** [comment]
It should actually point to `system76-cudnn-10.2` now

**Comment by ahoneybun** [comment]
@mmstick I'll fix that in a new PR though it looks like that closes this issue:

https://github.com/system76/docs/issues/266

Correct?

**Comment by ahoneybun** [comment]
@mmstick I set you as the reviewer of that PR.

**Pull request merged**
