### PR TITLE
CJDNS install, Minecraft Client, And Minecraft Server Setup Articles.

### PR DESCRIPTION
**Pull request by kylerschin**

### CODE REVIEW

**Comment by Xeboc** [comment]
Sorry for taking some time to get back to you about this!  It gets so busy around here!  I'd like to make a few edits if you don't mind.  Since we are an Ubuntu only shop, I was going to remove the additional sections about other operating systems, and I was going to adjust it to our style guide.  Would you be ok with me making some edits?  Or would you like to?  Thank you so much for the articles!  I'm sure other people will benefit from what you've written!

**Comment by kylerschin** [comment]
Awesome! That's okey dokey with me!

**Comment by kylerschin** [comment]
Umm... this.... it's been sitting here in the pull-repo dump for 40 days now.... @Xeboc

**Comment by Xeboc** [comment]
Ah, so it has!  I'll get this added this week.  Thanks for the reminder!

**Comment by Xeboc** [comment]
Added!  Thank you again for the articles.  We decided to create a community section with a reference back to your Github account as the contributer.  We welcome any more contributions, and I promise not to take so long to merge them next time!

**Comment by kylerschin** [comment]
Thanks so much! Maybe it's life in Denver, but that's another story. ;)

**Pull request closed without merging**
