### PR TITLE
Added line to tailwind.css for foldable headers.

### PR DESCRIPTION
**Pull request by gangwerz**
This PR adds a line to the `tailwind.css` stylesheet to allow the Markdown `#` headers to act as foldable sections.

Without the changes here, the folding `>` icon appears a line above the header's text.

### CODE REVIEW

**Review by storyaddict — APPROVED** [review]
We've tested this Live and it fixes the problem.

**Comment by jacobgkau** [comment]
I'm seeing Markdown headers not work when trying to test this:

image

How are you formatting it to see them work?

**Comment by jacobgkau** [comment]
It seems they work if surrounded by blank lines:

image

The vertical alignment's still a little off, but the carrot is next to the header:

image

**Comment by gangwerz** [comment]
The markdown parser makes things weird. As far as I can tell, we need a space before the `#` for it parse correctly...

```
<details>
<summary>
  
# Header
</summary>
<p>
</details>
```

**Review by jacobgkau — APPROVED** [review]
CSS is working to make the arrow appear on the same line as the header. We may want to tweak the vertical alignment further in the future.

**Comment by gangwerz** [comment]
I also confirmed headers inside the folded section work if they are preceded by a new line as well.

<details>
<summary>

# Header that _is_ the fold
</summary>

## Header inside the fold

here is where you would put the content you want to fold away
</details>

# Header after the fold

**Pull request merged**
