### PR TITLE
Updating Thelio power article

### PR DESCRIPTION
**Pull request by ahoneybun**
This PR updates the Thelio power article to include common questions that the happiness engineers would ask as well as link to tech-docs that show where the Thelio Io board power button.

### CODE REVIEW

**Comment by jacobgkau** [comment]
The current article is linked from various Thelio tech-docs manuals, e.g.: https://tech-docs.system76.com/models/thelio-mega-r1.0/repairs.html#troubleshooting-the-power-button 

If this PR changes the link of the article, please add a redirect or prepare an accompanying tech-docs PR to link to the appropriate section of the changed article.

**Comment by ahoneybun** [comment]
> The current article is linked from various Thelio tech-docs manuals, e.g.: https://tech-docs.system76.com/models/thelio-mega-r1.0/repairs.html#troubleshooting-the-power-button
> 
> If this PR changes the link of the article, please add a redirect or prepare an accompanying tech-docs PR to link to the appropriate section of the changed article.

I fixed the Mira link as well thanks for the catch!

**Comment by jacobgkau** [comment]
@ahoneybun The links in this article were not what I was referring to, I'm talking about the links _to_ this article from within the tech docs.

**Comment by ahoneybun** [comment]
> @ahoneybun The links in this article were not what I was referring to, I'm talking about the links _to_ this article from within the tech docs.

Ah sorry! I'll work on a tech-docs PR as well.

**Comment by jacobgkau** [comment]
I'm still confused why this information about general "is it plugged in" troubleshooting needs to be in the same article as specific instructions for replacing a specific component. You all obviously have the final say on support articles, but do you not think a troubleshooting article could be a new article instead of retrofitting this one?

**Comment by Socialhappiness** [comment]
@jacobgkau makes a good point. Let's make it a new article

**Comment by ahoneybun** [comment]
Going to do this though a new article instead so closing this PR.

**Pull request closed without merging**
