### PR TITLE
Use Denver time

### PR DESCRIPTION
**Pull request by btkostner**

### CODE REVIEW

**Comment by isantop** [comment]
"Mountain Time" is both more accurate and likely more helpful than "Denver Time" in case people don't know which time zone Denver is in.

**Comment by btkostner** [comment]
This was something Ben pointed out. Ask him.

**Comment by isantop** [comment]
I think we all agree here (@brs17 should comment so he's on record).

**Comment by brs17** [comment]
Had pointed out MDT should be Mountain time on the contact page. Fixed here: https://github.com/system76/joshua/commit/ececa2e73311f2451fb27fa0449488b7b03ad584

**Pull request closed without merging**
