### PR TITLE
Make the SMMStore article more generic

### PR DESCRIPTION
**Pull request by gangwerz**
I left the SMMStore information in the article. Then, restructured to allow this article to work for any firmware flash, but with info on the SMMStore if that should resurface. Also indicates to remove all drives if they are unable to reach the firmware boot menu.

### CODE REVIEW

**Review by thomas-zimmerman — APPROVED** [review]
This makes this more usable

**Review by jackpot51 — CHANGES_REQUESTED** [review]
This PR does not change the fact that the linked firmware images are specifically for clearing SMMStore, not for updating via USB. We would need new images that preserve the SMMStore for that.

**Comment by thomas-zimmerman** [comment]
@jackpot51 We've been using this article as a general overview how updating the firmware when we provide a USB image file with specific versions of firmware.

**Comment by jackpot51** [comment]
Also, if we did have links to firmware ZIP files here, who will be keeping those up to date?

**Comment by thomas-zimmerman** [comment]
We were thinking of how to stage a page for each model that has prior releases of the firmware. As I've been able to build release USB images, support would be adding those on request.

**Comment by jackpot51** [comment]
> We were thinking of how to stage a page for each model that has prior releases of the firmware. As I've been able to build release USB images, support would be adding those on request.

I would feel better if this page was copied instead of renamed, and all references to SMMstore clearing firmware were removed, including the links. That way the old page is still there for whoever needs to use these special firmware versions. They are not useful for newer firmwares since removing CMOS battery will do the same thing.

**Comment by gangwerz** [comment]
Moving to dedicated file for the USB firmware flashing. Closing out this PR without merging.

**Pull request closed without merging**
