### PR TITLE
Update Bluetooth troubleshooting commands for v22.04

### PR DESCRIPTION
**Pull request by cwsystem76**
Some of the instructions on this document no longer apply for Pop!OS v22.04, so I've split up those commands into a version for v22.04 and a verison for previous releases. I also added a note to the section about the `module-bluetooth-discover` Pulseaudio module, which is no longer used in v22.04.

### CODE REVIEW

**Review by ahoneybun — CHANGES_REQUESTED** [review]
We would need to update the Pop name to Pop!_OS you can use \ to escape the name for formatting.

**Comment by cwsystem76** [comment]
> We would need to update the Pop name to Pop!_OS you can use \ to escape the name for formatting.

Done.

**Review by storyaddict — APPROVED** [review]
These changes make sense and look correct.

**Review by Ampersandstorm — APPROVED** [review]
Looks good!

**Pull request merged**
