### PR TITLE
Add info on generic docking station.

### PR DESCRIPTION
**Pull request by GrueMaster**
I have updated this to reflect a new docking station I recently purchased and was able to get fully functional with my Galego Pro.  VGA doesn't appear to work (yet), but HDMI, Network, USB and SD reader all work.

### CODE REVIEW

**Comment by ahoneybun** [comment]
I'd like the docking station to be tested a bit more what happens if you suspend and resume? What if you have it plugged in and reboot? The VGA port is not working is a reason why I would not recommend it as we would want all the ports to work.

**Comment by GrueMaster** [comment]
I'll continue testing it and report here.  Not sure how to enable the VGA port as nothing about the dock shows up in /sys/bus/thunderbolt/devices.  I have tested this dock on another system (Asus), and it was visible then.  

I also briefly  tested a Thunderbolt USB-C HDMI adapter and it showed bus errors under kernel 4.15.

**Comment by GrueMaster** [comment]
Correction:  VGA does work.  My VGA cable went to a different monitor on my desk running HDMI from another system (too many cables).

Suspend/Resume work as expected.  Video fully recovers, network reconnected, usb mouse on dock works, etc.

Reboot takes a little longer as it detects the dock and establishes video settings accordingly.  If anything, the HiDPI daemon is thrown off and the laptop display is reduced to 1600x900 LoDPI.  This is with the latest HiDPI daemon from ppa:system76-stable on Ubuntu/Pop-OS 18.04.  The monitors I have are Asus 24" VE247H 1080 monitors.  I do not have any 4K monitors to test with.

Is there anything else I can test?

**Comment by ahoneybun** [comment]
I'm sorry for the delay, I believe we are going to redo the docking station article later on.

**Comment by jacobgkau** [comment]
The [link](https://www.pchcables.com/usb31tychubd.html) to this product now redirects to the manufacturer's home page. Their website has a single USB 3.1 dock listed, and it does not have VGA, so it does not appear to be the same model.

**Comment by GrueMaster** [comment]
The link was never to the manufacturer.  PCH Cables is a reseller (similar to Amazon, just local and I know the owner).  It was very generic, and didn't have a manual or drivers.  Just plug & play.  I'll see if I can dig up more info on it later this week.

**Comment by doomspork** [comment]
Sorry for the trouble @GrueMaster and @jacobgkau, this PR is still valid and should not have been closed. This mistake was a result of some new changes to how this project is built. Could we retarget this PR to `master` and reopen it? That should be all that's necessary.

**Comment by GrueMaster** [comment]
I'll try to refresh it and re-merge this weekend.  I also want to see if I can get a working link to the dock.

**Comment by doomspork** [comment]
@GrueMaster let me know if you have any issues with Git, I'd be happy to help however I can to get your PR squared away :muscle: 

Thanks again for getting involved :grin:

**Pull request closed without merging**
