### PR TITLE
Add Coreboot Configurator steps

### PR DESCRIPTION
**Pull request by ahoneybun**
This PR adds steps for using this tool to turn off the IME if the model supports it.

### CODE REVIEW

**Review by jacobgkau — DISMISSED** [review]
> Using the Coreboot Configurator you can turn off the Intel ME using the steps in [this article](https://github.com/system76/coreboot/tree/system76/util/coreboot-configurator) if your firmware version is higher then 2022-01-06 you can check the version with this command:

This is a run-on sentence and has an incorrect usage of "then."

**Review by Ampersandstorm — APPROVED** [review]
Thanks for adding these details.

**Review by leviport — APPROVED** [review]
Looks good!

**Review by thomas-zimmerman — APPROVED** [review]
Good to add.

**Pull request merged**
