### PR TITLE
Minor grammar changes

### PR DESCRIPTION
**Pull request by tangowithfoxtrot**
Changed "a" to "an" when referring to ovpn files

### CODE REVIEW

**Comment by jacobgkau** [comment]
I believe the reason "a" was used is because the "dot" in `.ovpn` is pronounced. You would say "a dot," not "an dot." That said, the ambiguity could be avoided by removing the leading `.` where possible and rewording the remaining instances.

**Comment by tangowithfoxtrot** [comment]
Fair enough. I always skip the "dot" in my head, but I can totally see it either way. Would changing the `Getting a .ovpn file` line to something like `Getting an OpenVPN (.ovpn) file` be agreeable, or would you prefer it be something like `Getting an ovpn file`?

**Comment by jacobgkau** [comment]
> Would changing the `Getting a .ovpn file` line to something like `Getting an OpenVPN (.ovpn) file` be agreeable

That suggestion looks great to me for the headers, as long as we either roll back the changes to the body text or reword it similarly in the body.

**Comment by tangowithfoxtrot** [comment]
I've submitted new commits with revised grammar edits. Let me know if any further revision is necessary.

**Review by jacobgkau — APPROVED** [review]

**Pull request merged**
