### PR TITLE
removed atom since it will be sunset soon

### PR DESCRIPTION
**Pull request by jawadnassar**
updated [Switching from macOS to Pop!_OS](https://support.system76.com/articles/switch-from-macos-to-popos/) to remove Atom text editor from it, since it will be sunset soon

### CODE REVIEW

**Review by jacobgkau — APPROVED** [review]
Citation: https://github.blog/2022-06-08-sunsetting-atom/ 

Perhaps we could add some alternative IDE options in the future (JetBrains/IntelliJ options might be worth listing, or some lightweight Rust options such as Lapce have been popping up recently), but this one makes sense to remove.

**Comment by jackpot51** [comment]
😭

**Review by jackpot51 — APPROVED** [review]

**Comment by jawadnassar** [comment]
Replace Atom with Sublime and uploaded its screenshot

**Review by leviport — APPROVED** [review]

**Comment by leviport** [comment]
Thanks for the contribution!

**Pull request merged**
