### PR TITLE
Added Docs for Instaling the OpenSpades Game

### PR DESCRIPTION
**Pull request by 0verk1ll**

### CODE REVIEW

**Comment by jackpot51** [comment]
This is documentation that is not very relevant to System76 customers, and is better suited to going on the OpenSpades website, which is also editable on GitHub: https://github.com/yvt/openspades/tree/gh-pages

**Comment by 0verk1ll** [comment]
What are your criteria for the community articles section of the support page? I thought OpenSpades would be relevant since Minetest and Minecraft both have documentation pages.

**Comment by jackpot51** [comment]
If you would like to add this to the Community Articles section, you will need to fill in the following at the beginning of the MD file:

```
---
layout: article
title: TODO TITLE
description: 
  TODO DESCRIPTION
keywords:
  - TODO
  - KEYWORDS
hidden: false
section: community
---
```

Please see the cjdns article for an example. Otherwise, it would be assumed to be a support article, which are distribution and hardware related.

**Comment by jackpot51** [comment]
Looks good now - thanks!

**Pull request merged**
